app_core/app_core/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path("", include("index.urls")),

    #app_productos_CRUD
    path('', include(("app_productos.urls","app_productos"), namespace="app_productos")),
    #app_usuarios_CRUD
    path('', include(("app_usuarios.urls","app_usuarios"), namespace="app_usuarios")),
]

app_core/app_productos/urls.py
from django.urls import path
from .views import listar_productos , create_productos , update_productos , delete_productos , detalle_producto

app_name = "app_productos"

urlpatterns = [
    path('listar_productos/', listar_productos, name="listar_productos"),
    path('crear_productos/', create_productos, name="create_productos"),
    path('actualizar_productos/<int:pk>/', update_productos, name="update_productos"),
    path('eliminar_productos/<int:pk>/', delete_productos, name="delete_productos"),
    path('detalle_producto/<int:pk>/', detalle_producto, name='detalle_producto'),
]

app_core/app_usuarios/urls.py
from django.urls import path 
from .views import UserLoginView , PanelView , UserListView , UserCreateView , UserUpdateView , logout_view

app_name = "app_usuarios"

urlpatterns = [
    path("login/", UserLoginView.as_view() , name="login"),
    path("panel/", PanelView.as_view() , name="panel"),
    path("usuario_list/", UserListView.as_view() , name="usuario_list"),
    path("usuario_create/", UserCreateView.as_view() , name="usuario_create"),
    path("usuario_edit/<int:pk>/", UserUpdateView.as_view() , name="usuario_edit"),
    path('logout/', logout_view, name='logout'),
]

app_core/index/urls.py
from django.urls import path 
from .views import index , about


app_name = "index"

urlpatterns = [
    path("", index, name="index"),
    path("about/", about, name="about"),
]

app_core/app_productos/models.py
from django.db import models

# Create your models here.

class Producto(models.Model):
    nombre_producto = models.CharField(max_length=200)
    descripcion_producto = models.CharField(max_length=9999, default="Sin descripción")
    precio_producto = models.IntegerField()
    
    def __str__(self):
        return (f"{self.nombre_producto} - {self.precio_producto}")

app_core/app_usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

app_core/index/models.py
from django.db import models

# Create your models here.

app_core/app_productos/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ["nombre_producto","descripcion_producto","precio_producto"]
        widgets = {}

app_core/app_usuarios/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm , UserChangeForm , AuthenticationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username","password1","password2","email","first_name","last_name")


class CustomUserChangeForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ["username","email","first_name","last_name",]

app_core/app_productos/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .forms import ProductoForm
from .models import Producto
from django.contrib.auth.decorators import login_required
# Create your views here.

#Listar los producto
def listar_productos(request):
    productos = Producto.objects.all()
    contexto = {"productos":productos}
    return render(request,"app_productos/producto_list.html",contexto)

#Mostrar los productos
def detalle_producto(request, pk):
    producto = get_object_or_404(Producto, id=pk)
    return render(request, 'app_productos/detalle_producto.html', {'producto': producto})

#Crear un producto siempre y cuando este logeado el usuario
@login_required
def create_productos(request):
    if request.method == "POST":
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("app_productos:listar_productos")
    else:
        form = ProductoForm()
        contexto = {"form":form}
    return render(request,"app_productos/producto_create.html",contexto)

#Cambios en el producto siempre y cuando este logeado el usuario
@login_required
def update_productos(request, pk):
    producto = get_object_or_404(Producto,pk=pk)
    if request.method == "POST":
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
            return redirect("app_productos:listar_productos")
    else:
        form = ProductoForm(instance=producto)
        contexto = {"form":form}
    return render(request,"app_productos/producto_update.html",contexto)

#Borrar un producto siempre y cuando este logeado el usuario
@login_required
def delete_productos(request, pk):
    producto = get_object_or_404(Producto,pk=pk)
    if request.method == "POST":
        producto.delete()
        return redirect("app_productos:listar_productos")
    contexto = {"producto":producto}
    return render(request, "app_productos/producto_delete.html", contexto)

app_core/app_usuarios/views.py
from django.views.generic import ListView , CreateView, UpdateView , TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import CustomUserChangeForm , CustomUserCreationForm
from django.contrib.auth import logout

# Create your views here.
#Login
class UserLoginView(LoginView):
    template_name = "app_usuarios/login.html"
#Vista panel
class PanelView(LoginRequiredMixin, TemplateView):
    template_name = "app_usuarios/panel.html"

#listar los usuarios
class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = "app_usuarios/usuario_list.html"
    context_object_name = "users"

#crear usuario
class UserCreateView(CreateView):
    model = User
    form_class = CustomUserCreationForm
    template_name = "app_usuarios/usuario_create.html"
    success_url = reverse_lazy("app_usuarios:usuario_list")

#Cambios en el usuario
class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name = "app_usuarios/usuario_edit.html"
    success_url = reverse_lazy("app_usuarios:usuario_list")

#definicion para el logout
def logout_view(request):
    logout(request)
    return redirect('index:index')  # Cambia 'index:index' por la URL a la que quieres redirigir

app_core/index/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "index/index.html")

def about(request):
    return render(request, "index/about.html")

app_core/app_productos/templates/app_productos/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock title %}
    </title>
</head>
<body>
    <head>

    </head>
    
    <nav>

    </nav>
    
    <aside>

    </aside>
    
    <main>
        <h1>PRODUCTOS</h1>
        {% block content %}
        
        {% endblock content %}
    </main>

    <footer>

    </footer>

</body>
</html>

app_core/app_productos/templates/app_productos/detalle_producto.html
{% extends "app_productos/base.html" %}

{% block title %}DETALLE PRODUCTO{% endblock title %}

{% block content %}
<h1>{{ producto.nombre }}</h1>
    <p>{{ producto.descripcion_producto }}</p>
    <p>Precio: ${{ producto.precio_producto }}</p>
    <a href="{% url 'app_productos:listar_productos' %}">Volver a la lista de los productos</a>

{% endblock content%}

app_core/app_productos/templates/app_productos/producto_create.html
{% extends "app_productos/base.html" %}

{% block title %}Crear Producto{% endblock title %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
    <input type="reset" value="Limpiar">
    <button><a href="{% url 'app_productos:listar_productos' %}">CANCELAR</a></button>
</form>

{% endblock content%}

app_core/app_productos/templates/app_productos/producto_delete.html
{% extends "app_productos/base.html" %}

{% block title %}Eliminar Producto{% endblock title %}

{% block content %}
<p>NOMBRE DEL PRODUCTO: {{ producto.nombre_producto }}</p>
<p>DESCRIPCION DEL PRODUCTO: {{ producto.descripcion_producto }}</p>
<p>PRECIO:$ {{ producto.precio_producto }}</p>
<form method="POST">
    {% csrf_token %}
    <p>¿Desea realmente elminar el elemento?</p>
    {{ form.as_p }}
    <input type="submit" value="Eliminar">
    <button><a href="{% url 'app_productos:listar_productos' %}">Cancelar</a></button>
</form>

{% endblock content%}

app_core/app_productos/templates/app_productos/producto_list.html
{%extends "index/index.html"%}

{% block title %}Productos{% endblock title %}

{% block content %}
<h1>Productos</h1>
<button><a href="{% url 'app_productos:create_productos' %}">CREAR PRODUCTO</a></button>
{%for producto in productos %}
        <article style="border: solid 1px black;margin:5px;">
            <p> {{producto.nombre_producto}} </p>
            <p>Precio: $ {{producto.precio_producto}} </p>
            <button><a href="{% url 'app_productos:detalle_producto' pk=producto.id %}">VER MAS...</a></button>
            <button><a href="{% url 'app_productos:update_productos' pk=producto.id %}">ACTUALIZAR</a></button>
            <button><a href="{% url 'app_productos:delete_productos' pk=producto.id %}">ELIMINAR</a></button>
        </article>
{%endfor%}

{% endblock content%}

app_core/app_productos/templates/app_productos/producto_update.html
{% extends "app_productos/base.html" %}

{% block title %}Actualizar Producto{% endblock title %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Actualizar</button>
    <button><a href="{% url 'app_productos:listar_productos' %}">CANCELAR</a></button>

</form>

{% endblock content%}

app_core/app_usuarios/templates/app_usuarios/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %} App Usuarios {% endblock title %}
    </title>
    <style>
        /* Estilos básicos para la barra de navegación */
        nav {
            background-color: #333;
            color: white;
            padding: 10px;
        }
        nav ul {
            list-style: none;
            margin: 0;
            padding: 0;
            display: flex;
        }
        nav ul li {
            margin: 0 15px;
        }
        nav ul li a {
            color: white;
            text-decoration: none;
            font-weight: bold;
        }
        nav ul li a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'index:index' %}">Inicio</a></li>
            <li><a href="{% url 'app_usuarios:panel' %}">Panel</a></li>
            <li><a href="{% url 'app_usuarios:usuario_list' %}">Listado de Usuarios</a></li>
            </ul>
    </nav>
    <main>
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{message}}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% block content %}
        {% comment %} Aqui va a ir todo el contendio cuando haga un extends de la plantilla base.html {% endcomment %}
        {% endblock content %}
    </main>

    <footer>

    </footer>

</body>
</html>

app_core/app_usuarios/templates/app_usuarios/login.html
{% extends 'app_usuarios/base.html' %}

{% block title %}Login{% endblock title %}

{% block content %}
<h1>Login</h1>

<form method="post">
    {% csrf_token %}
    {{ form.none_field_errors }}
    <div>
        {{ form.username.label_tag }}
        {{ form.username }}
        {{ form.username.errors }}
    </div>
    <div>
        {{ form.password.label_tag }}
        {{ form.password }}
        {{ form.password.errors }}
    </div>
    <button type="submit">Log-In</button>
</form>
{% endblock content %}

app_core/app_usuarios/templates/app_usuarios/panel.html
{% extends 'app_usuarios/base.html' %}

{% block title %}Login{% endblock title %}
{% block content %}
<h1> Bienvenido al panel, {{ user.username }} </h1>
<a href="{% url 'app_usuarios:usuario_create' %}">CREAR NUEVO USUARIO</a>

{% endblock content%}

app_core/app_usuarios/templates/app_usuarios/usuario_create.html
{% extends "app_usuarios/base.html" %}

{% block title %}Crear Usuario{% endblock title %}

{% block content %}
<h1>CREAR USUARIO</h1>
<form method="POST">
    {{ form.none_field_errors }}
    {% csrf_token %}
    {{ form.as_div }}
    <input type="submit" value="Guardar">
    <input type="reset" value="Limpiar">
    <button><a href="{% url 'app_usuarios:panel' %}">CANCELAR</a></button>
</form>

{% endblock content%}

app_core/app_usuarios/templates/app_usuarios/usuario_delete.html
{% extends "app_usuarios/base.html" %}

{% block title %}Eliminar Usuario{% endblock title %}

{% block content %}
<p>NOMBRE: {{ username }}</p>
<p>EMAIL: {{ user.email }}</p>
<form method="POST">
    {% csrf_token %}
    <p>¿Desea realmente elminar el usuario?</p>
    {{ form.as_p }}
    <input type="submit" value="Eliminar">
    <button><a href="{% url 'app_usuarios:listar_usuarios' %}">Cancelar</a></button>
</form>

{% endblock content%}

app_core/app_usuarios/templates/app_usuarios/usuario_edit.html
{% extends "app_usuarios/base.html" %}

{% block title %}EDITAR USUARIO{% endblock title %}

{% block content %}
<h1>EDITAR USUARIO</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_div }}
    <button type="submit">GUARDAR CAMBIOS</button>
</form>
{% endblock content%}

app_core/app_usuarios/templates/app_usuarios/usuario_list.html
{%extends "app_usuarios/base.html"%}

{% block title %}Lista de Usuarios{% endblock title %}

{% block content %}
<h1>LISTA DE USUARIOS</h1>
{% comment %} Link para crear {% endcomment %}
<table border="1">
    <thead>
        <tr>
            <th>ID</th><th>USERNAME</th><th>EMAIL</th><th>ACCIONES</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{user.id}}</td>
            <td>{{user.username}}</td>
            <td>{{user.email}}</td>
            <td>
                <a href="{% url 'app_usuarios:usuario_edit' user.id%}">EDITAR</a>
                {# link para eliminar #}
            </td>
        </tr>
        {% endfor %}
    </tbody>

</table>

{% endblock content%}

app_core/index/templates/index/about.html
{% extends 'index/index.html' %}

{% block title %}ACERCA DE MI{% endblock title %}
{% block content %}
<p>
    Hola y bienvenido a mi primera pagina hecha con Django, programando con Python
</p>
<p> 
    Mi nombre es Julian Monteiro Guerra, y he cursado a lo largo de 3 meses en CoderHouse el curso de Python con la posibilidad
    de seguir adentrándome en el mundo de la programación para base de datos.
</p>
<p>
    En este proyecto, he creado una página tipo "BLOG", en donde se pueden mostrar, agregar y eliminar productos de hardware para PC. La interaccion de agregar y eliminar, puede realizarse siempre y cuando estés logeado, de lo contrario no
    te dejaría hacer ningún cambio en la página.
</p>
<p>
    Dicho esto, espero que se entienda el funcionamiento de la misma, y que guste la interacción de la página.
</p>

{% endblock content %}

app_core/index/templates/index/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}Inicio{% endblock title %}
    </title>
    <style>
        /* Estilos básicos para la barra de navegación */
        nav {
            background-color: #333;
            color: white;
            padding: 10px;
        }
        nav ul {
            list-style: none;
            margin: 0;
            padding: 0;
            display: flex;
        }
        nav ul li {
            margin: 0 15px;
        }
        nav ul li a {
            color: white;
            text-decoration: none;
            font-weight: bold;
        }
        nav ul li a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'index:index' %}">Inicio</a></li>
            <li><a href="{% url 'app_productos:listar_productos' %}">Productos</a></li>
            <li><a href="{% url 'app_usuarios:login' %}">Log-In</a></li>
            <li><a href="{% url 'index:about' %}">Acerca de Mi</a></li>
            <li><a href="{% url 'app_usuarios:usuario_create' %}">Crear Usuario</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'app_usuarios:logout' %}">Log-Out</a></li>
                <li><a href="{% url 'app_usuarios:usuario_list' %}">Listado de Usuarios</a></li>
            {% endif %}
            <li><a href="/admin/">Admin</a></li>
            
        </ul>
    </nav>
    <main>
        <h1>Bienvenido a mi primera página</h1>
        {% block content %}

        {% endblock content%}
    </main>

</body>
</html>